[project]
name = "klik"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "customtkinter>=5.2.2",
    "pillow>=11.3.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.10",
]
